on:
  push:
    branches:
      - master

name: Deploy and Invalidate

jobs:
  deploy:
    name: Begin Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
